CREATE TABLE accounts
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    customer_id BIGINT                                  NOT NULL,
    balance     DECIMAL(19, 2)                          NOT NULL,
    CONSTRAINT pk_accounts PRIMARY KEY (id)
);

CREATE TABLE cards
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account_id BIGINT,
    masked_pan VARCHAR(32)                             NOT NULL,
    is_locked  BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_cards PRIMARY KEY (id)
);

CREATE TABLE customers
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    full_name VARCHAR(255)                            NOT NULL,
    CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE transactions
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    from_account_id BIGINT                                  NOT NULL,
    to_account_id   BIGINT                                  NOT NULL,
    amount          DECIMAL(19, 2)                          NOT NULL,
    description     VARCHAR(500),
    created_at      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_transactions PRIMARY KEY (id)
);

ALTER TABLE cards
    ADD CONSTRAINT uk_cards_masked_pan UNIQUE (masked_pan);

ALTER TABLE accounts
    ADD CONSTRAINT FK_ACCOUNTS_ON_CUSTOMER FOREIGN KEY (customer_id) REFERENCES customers (id);

ALTER TABLE cards
    ADD CONSTRAINT FK_CARDS_ON_ACCOUNT FOREIGN KEY (account_id) REFERENCES accounts (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_FROM_ACCOUNT FOREIGN KEY (from_account_id) REFERENCES accounts (id);

ALTER TABLE transactions
    ADD CONSTRAINT FK_TRANSACTIONS_ON_TO_ACCOUNT FOREIGN KEY (to_account_id) REFERENCES accounts (id);